version: '3.8'

services:
   db2:
     image: mysql
     volumes:
       - db2_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
      ports:
      - "9906:3306"


   wordpress:
     depends_on:
       - db2
     image: wordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_db2_HOST: db2:3306
       WORDPRESS_db2_USER: wordpress
       WORDPRESS_db2_PASSWORD: wordpress
       WORDPRESS_db2_NAME: wordpress
volumes:
    db2_data: {}

